password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from website import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/login/', views.MyLoginView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api', include('rest_framework.urls'))

]

website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('add/', views.AddCredentialView.as_view(), name='add'),
    path("vault/", views.VaultView.as_view(), name="vault"),
    path("vault/delete/<int:pk>", views.DeleteCredentialView.as_view(), name="delete_credential"),
    path("vault/edit/<int:pk>", views.edit_credential, name="edit_credential"),
    path('profile/<int:pk>', views.UserProfileView.as_view(), name="profile"),
    path('profile/edit/<int:pk>', views.UserProfileEditView.as_view(), name="edit_profile")
]

website/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Credential(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    credential_name= models.CharField(max_length=128) 
    credential_url= models.URLField(max_length=200, null=True, blank=True)
    credential_login = models.CharField(max_length=128)
    credential_password = models.CharField(max_length=512)
    def __str__(self):
        return self.user.username+': '+self.credential_name
    class Meta:
        ordering = ['id']

website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from crispy_forms.layout import Layout, Submit
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper


from . import models


class UserForm(forms.ModelForm):
    email = forms.EmailField()    
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", )
        help_texts = {
            'username': None
        }



class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.exclude(
            pk=self.instance.pk).filter(email__iexact=email)
        if qs.exists():
            raise ValidationError(
                'A user with this email address already exists.')
        return email
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Password Confirmation'

        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        help_texts = {
            'username': None
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.exclude(
            pk=self.instance.pk).filter(email__iexact=email)
        if qs.exists():
            raise ValidationError(
                'A user with this email address already exists.')
        return email


class AddCredentialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'credential_name',
            'credential_url',
            'credential_login',
            AppendedText('credential_password', mark_safe(
                '<i class="fa-solid fa-eye-slash" id="togglePassword" style="cursor: pointer;"></i>')),
            self.helper.add_input(Submit('submit', 'Add credential'))    
        )
        self.edit_helper = FormHelper()
        self.edit_helper.form_tag = False 
        self.edit_helper.layout = Layout(
            AppendedText('credential_password', mark_safe(
                '<i class="fa-solid fa-eye-slash" id="togglePassword" style="cursor: pointer;"></i>')),

        )

    class Meta:
        model = models.Credential
        fields = ('credential_name', 'credential_url', 'credential_login',
                  'credential_password',)
        labels = {
            'credential_name': 'Website or app name',
            'credential_url': 'Link to the website',
            'credential_login': 'Email or login',
            'credential_password': 'Password'
        }
        widgets = {
            'credential_password': forms.PasswordInput(),
        }

website/views.py
from django.http import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.cache import cache_control
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User


from .encryption import Encryption
from . import models
from . import forms
# Create your views here.


class MainView(TemplateView):
    template_name = 'website/index.html'


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'website/profile.html'


class UserProfileEditView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.UserForm
    template_name = 'website/profile.html'

    def get_success_url(self) -> str:
        return reverse_lazy('profile', kwargs={'pk': self.request.user.pk})

    def dispatch(self, request, *args, **kwargs):
        if request.user.pk != self.kwargs.get('pk'):
            messages.error(request, 'You can\'t edit other users profile')
            return redirect('index')
        return super().dispatch(request, *args, **kwargs)
    



class VaultView(LoginRequiredMixin, ListView):
    model = models.Credential
    template_name = 'website/password_vault.html'

    def get_queryset(self):
        return models.Credential.objects.filter(user=self.request.user)

    def get(self, request: HttpRequest):
        if request.session.get('show_second_modal', None):
            encryption = Encryption()
            cred_pk = request.session['cred_pk']
            context = self.get_context_data(
                object_list=models.Credential.objects.filter(user=self.request.user))
            context['credential_password'] = encryption.decrypt_data(self.model.objects.filter(
                user=self.request.user).get(pk=cred_pk).credential_password)
            context['show_second_modal'] = True
            request.session.pop('show_second_modal', None)
            request.session.pop('cred_pk', None)
            return render(request, self.template_name, context)
        return super().get(request)

    def post(self, request):
        password = request.POST.get('password')

        check = request.user.check_password(password)
        if not check:
            messages.error(request, 'Incorrect password!',
                           extra_tags='vault_error')
        else:
            cred_pk = request.POST.get('credential_pk')

            # Create session variables to handle successful POST without rendering template with context, that way we avoid form resubmission
            request.session['show_second_modal'] = True
            request.session['cred_pk'] = cred_pk
        return redirect('vault')
        # return render(request, self.template_name, {'credential_list': self.model.objects.all(), 'check': check, 'credential_password': credential_password})

    @method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True))
    def dispatch(self, request: HttpRequest, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class SignUpView(CreateView):
    form_class = forms.SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('index')
        return render(request, self.template_name, {'form': self.form_class})


class MyLoginView(LoginView):
    def get(self, request):
        form = self.form_class
        if request.user.is_authenticated:
            return redirect('index')
        return render(request, self.template_name, {'form': form})


class AddCredentialView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('add')
    form_class = forms.AddCredentialForm
    template_name = 'website/add_credential.html'

    def form_valid(self, form):
        credential = form.save(commit=False)
        credential.user = self.request.user

        encryption = Encryption()

        credential.credential_password = encryption.encrypt_data(
            credential.credential_password)
        credential.save()
        messages.success(
            self.request, 'Credential was added successfully.', extra_tags='added_credential')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, 'The form was not submitted successfully.', extra_tags='failed_add_credential')
        return super().form_valid(form)


@login_required
def edit_credential(request, pk):
    credential = get_object_or_404(models.Credential, pk=pk)
    encryption = Encryption()
    if request.method == 'POST':
        form = forms.AddCredentialForm(request.POST, instance=credential)
        if form.is_valid():
            credential.credential_password = encryption.encrypt_data(
                credential.credential_password)
            credential.save()
            form.save()
        else:
            messages.error(
                request, 'The form was not submitted successfully.', extra_tags='vault_error')
        return redirect('vault')
    else:
        form = forms.AddCredentialForm(instance=credential)
        form.data['credential_password'] = ''
        return render(request, 'website/password_vault.html', {'form': form, 'edit_pk': pk, 'credential_list': models.Credential.objects.filter(user=request.user)})


class DeleteCredentialView(LoginRequiredMixin, DeleteView):
    model = models.Credential
    success_url = reverse_lazy('vault')

templates/website/add_credential.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container p-5 mx-auto">
    {% if messages %}
      {% for message in messages %}
        {% if 'failed_add_credential' in message.tags %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% elif 'added_credential' in message.tags %}
          <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endif %}
      {% endfor %}
    {% endif %}
    <h1 class="my-5">Add credentials to password vault</h1>
    <div class="row">
      <div class="col-md-6">
        {% crispy form %}
      </div>
    </div>
  </div>
  <script>
    const togglePassword = document.querySelector('#togglePassword')
    const password = document.querySelector('#id_credential_password')
    
    togglePassword.addEventListener('click', () => {
      // Toggle the type attribute using
      // getAttribure() method
      const type = password.getAttribute('type') === 'password' ? 'text' : 'password'
      password.setAttribute('type', type)
      // Toggle the eye and bi-eye icon
      togglePassword.classList.toggle('fa-eye-slash')
      togglePassword.classList.toggle('fa-eye')
    })
  </script>
{% endblock %}

templates/website/index.html
{% extends 'base.html' %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      {% if 'error' in message.tags %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% else %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
      {% endif %}
    {% endfor %}
  {% endif %}

  <div class="container">
    <div class="jumbotron jumbotron-fluid">
      <h1>Password Keeper</h1>
      <p class="lead">Securely store and manage your online credentials</p>
      <hr class="my-4" />
      <p class="text-muted">With features like:</p>
      <ul class="list-group">
        <li class="list-group-item">Password Vault</li>
        <li class="list-group-item">Credential Name and URL Storage</li>
        <li class="list-group-item">Email or Login Credential Storage</li>
        <li class="list-group-item">Show credential password secured way</li>
        <li class="list-group-item">Edit or Delete Credentials as needed</li>
        <li class="list-group-item">Easy profile editing</li>
      </ul>
    </div>
  </div>
{% endblock %}

templates/website/password_vault.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container mx-auto">
    {% if messages %}
      {% for message in messages %}
        {% if 'vault_error' in message.tags %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>
  <div class="justify-content-center">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Credential name</th>
          <th scope="col">Credential URL</th>
          <th scope="col">Email/Login</th>
          <th scope="col">Password</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for elem in credential_list %}
          <tr>
            {% if elem.pk == edit_pk %}
              <form method="POST">
                {% csrf_token %}
                <td>{{ forloop.counter }}</td>
                <td>{{ form.credential_name|as_crispy_field }}</td>
                <td>{{ form.credential_url|as_crispy_field }}</td>
                <td>{{ form.credential_login|as_crispy_field }}</td>
                <td>
                  {% crispy form form.edit_helper %}
                </td>
                <td>
                  <button type="submit" class="btn btn-success">Save changes</button>
                  <button type="button" class="btn btn-danger" onclick="window.location.href='{% url 'vault' %}'">Cancel</button>
                </td>
              </form>
            {% else %}
              <td>{{ forloop.counter }}</td>
              <td>{{ elem.credential_name }}</td>
              {% if elem.credential_url != None %}
                <td>
                  <a href="{{ elem.credential_url }}">{{ elem.credential_url }}</a>
                </td>
              {% else %}
                <td>{{ elem.credential_url }}</td>
              {% endif %}
              <td>{{ elem.credential_login }}</td>
              <td>
                <div class="modal fade" id="ModalToggle-{{ forloop.counter }}" aria-hidden="true" aria-labelledby="ModalToggleLabel-{{ forloop.counter }}" tabindex="-1">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="ModalToggleLabel-{{ forloop.counter }}">Enter your keeper user password</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <form method="POST">
                        {% csrf_token %}
                        <div class="modal-body">
                          <label for="inputPassword-{{ forloop.counter }}" class="form-label">Password</label>
                          <div class="input-group">
                            <input type="password" id="inputPassword-{{ forloop.counter }}" name="password" class="form-control" />
                            <span class="input-group-text"><i class="fas fa-eye-slash" id="inputPassword-{{ forloop.counter }}" style="cursor: pointer;" onclick="toggleEye(this, 'inputPassword-{{ forloop.counter }}')"></i></span>
                            <input type="hidden" name="credential_pk" value="{{ elem.pk }}" />
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button type="submit" class="btn btn-primary" data-bs-toggle="modal">Submit</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                <button class="btn btn-primary" data-bs-target="#ModalToggle-{{ forloop.counter }}" data-bs-toggle="modal">Show password</button>
              </td>
              <td>
                <form class="d-inline" method="GET" action="{% url 'edit_credential' elem.pk %}">
                  <button type="submit" class="btn btn-info">Edit</button>
                </form>
                <form class="d-inline" method="POST" action="{% url 'delete_credential' elem.pk %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if show_second_modal %}
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Your password</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">Here is your password: {{ credential_password }}</div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <script>
      jQuery(document).ready(function () {
        jQuery('#staticBackdrop').modal('show')
      })
    </script>
  {% endif %}
  <script>
    const togglePassword = document.querySelector('#togglePassword')
    const password = document.querySelector('#id_credential_password')
    
    togglePassword.addEventListener('click', () => {
      // Toggle the type attribute using
      // getAttribure() method
      const type = password.getAttribute('type') === 'password' ? 'text' : 'password'
      password.setAttribute('type', type)
      // Toggle the eye and bi-eye icon
      togglePassword.classList.toggle('fa-eye-slash')
      togglePassword.classList.toggle('fa-eye')
    })
    
    function toggleEye(icon, passwordfieldId) {
      passwordfieldId = document.getElementById(passwordfieldId)
      const type = passwordfieldId.getAttribute('type') === 'password' ? 'text' : 'password'
      passwordfieldId.setAttribute('type', type)
      icon.classList.toggle('fa-eye-slash')
      icon.classList.toggle('fa-eye')
    }
  </script>
{% endblock %}

templates/website/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <h3 class="card-header">User Profile</h3>
          {% if form %}
            <form method="POST" action="{% url 'edit_profile' request.user.pk %}">
              {% csrf_token %}
              <div class="card-body">
                <p>
                  <strong>{{ form.username|as_crispy_field }}</strong>
                </p>
                <p>
                  <strong>{{ form.first_name|as_crispy_field }}</strong>
                </p>
                <p>
                  <strong>{{ form.last_name|as_crispy_field }}</strong>
                </p>
                <p>
                  <strong>{{ form.email|as_crispy_field }}</strong>
                </p>
                <p>
                  Date joined: <strong>{{ user.date_joined }}</strong>
                </p>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-success">Save changes</button>
                <button type="button" class="btn btn-danger mx-3" onclick="window.location.href='{% url 'profile' request.user.pk %}'">Cancel</button>
              </div>
            </form>
          {% else %}
            <div class="card-body">
              <p class="py-2">
                Username: <strong>{{ user.username }}</strong>
              </p>
              <p class="py-2">
                First name: <strong>{{ user.first_name|default:'Empty' }}</strong>
              </p>
              <p class="py-2">
                Last name: <strong>{{ user.last_name|default:'Empty' }}</strong>
              </p>
              <p class="py-2">
                Email: <strong>{{ user.email }}</strong>
              </p>
              <p class="py-2">
                Date joined: <strong>{{ user.date_joined }}</strong>
              </p>
            </div>
            <div class="card-footer">
              {% if request.user.pk == user.pk %}
                <a href="{% url 'edit_profile' user.pk %}" class="btn btn-info">Edit</a>
                <a href="{% url 'password_change' %}" class="btn btn-success mx-3">Change password</a>
              {% endif %}
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}